# Site settings
title: 欢迎来到地狱火的主页
email: 2487935515@qq.com
description: >-
  刘博文20231060079第十组的个人主页。
  这里是地狱火的领地，欢迎来到我的世界！
baseurl: ""
url: "https://Diyuhuo666.github.io"
github_username: Diyuhuo666
author: 刘博文

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  date_format: "%Y-%m-%d"
  social_links:
    - { platform: github, user_url: "https://github.com/Diyuhuo666" }

# Exclude from build
exclude:
  - README.md
  - docker-compose.yml
  - Gemfile.lock
